### PR TITLE
Update to aws-sdk v3.

### PR DESCRIPTION
**Pull request by martinj**
Test against node 18
Add types

### CODE REVIEW

**Review by aptomaKetil — COMMENTED** [review]
Why not use the simplified client? I.e. the export named `SQS` instead of `SQSClient`. Then you can do `client.deleteMessage({...})` instead of `client.send(new DeleteMessage({...}))`.

**Comment by martinj** [comment]
did know there was a simplified

**Review by aptomaKetil — APPROVED** [review]
Ok, I'll leave it up to you what you want to use. Personally I find the low-level client to produce incredibly ugly code.

**Comment by martinj** [comment]
I don't mind it and i prefer to use what they seem to recommend. Found it a bit funny i missed that it even existed, and i went through the docs yesterday. Checked again it does exists but it sort of hidden. All examples are shown in the new syntax. 

For modules its highly recommended to use new syntax its more performant and better for bundlers, less bundle sizes. Not sure but i think simple clients are generated on the fly with smithy if you use it. I guess this was added to help with migration.

**Pull request merged**
